# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "counters", :force => true do |t|
    t.column "html_count",  :integer,  :null => false
    t.column "rss_count",   :integer,  :null => false
    t.column "api_count",   :integer,  :null => false
    t.column "target_date", :datetime, :null => false
  end

  add_index "counters", ["id"], :name => "index_counters_on_id"

  create_table "taste_entries", :force => true do |t|
    t.column "user_id", :integer, :null => false
  end

  add_index "taste_entries", ["id"], :name => "index_taste_entries_on_id"
  add_index "taste_entries", ["user_id"], :name => "index_taste_entries_on_user_id"

  create_table "user_keywords", :force => true do |t|
    t.column "taste_entry_id", :integer, :null => false
    t.column "keyword",        :string,  :null => false
    t.column "tfidf_value",    :float,   :null => false
  end

  add_index "user_keywords", ["id"], :name => "index_user_keywords_on_id"
  add_index "user_keywords", ["keyword"], :name => "index_user_keywords_on_keyword"

  create_table "user_preferences", :force => true do |t|
    t.column "user_id",              :integer, :null => false
    t.column "point_threthold",      :integer
    t.column "simirality_threthold", :integer
    t.column "arrange_entry_count",  :integer
    t.column "hatebu_name",          :string
    t.column "is_use_hatebu_learn",  :boolean
  end

  add_index "user_preferences", ["id"], :name => "index_user_preferences_on_id"
  add_index "user_preferences", ["user_id"], :name => "index_user_preferences_on_user_id"

  create_table "users", :force => true do |t|
    t.column "nickname",     :string,   :null => false
    t.column "password",     :string,   :null => false
    t.column "name",         :string,   :null => false
    t.column "mail_address", :string,   :null => false
    t.column "age",          :integer,  :null => false
    t.column "regist_at",    :datetime, :null => false
  end

  add_index "users", ["id"], :name => "index_users_on_id"
  add_index "users", ["nickname"], :name => "index_users_on_nickname"

end
